Repository suyoungSwim/spring-vote-21st, pull requests merged in 2025-05, with the labels that each got.

#12 [FEAT] 투표기능 개발 - 엔티티 CRUD 서비스 구현
  README.md
  src/main/java/com/ceos/spring_vote_21st/auth/config/SecurityConfig.java
  src/main/java/com/ceos/spring_vote_21st/member/domain/CeosPosition.java
  src/main/java/com/ceos/spring_vote_21st/member/domain/CeosTeam.java
  src/main/java/com/ceos/spring_vote_21st/member/domain/Member.java
  src/main/java/com/ceos/spring_vote_21st/member/repository/MemberRepository.java
  src/main/java/com/ceos/spring_vote_21st/member/service/MemberService.java
  src/main/java/com/ceos/spring_vote_21st/member/web/MemberController.java
  src/main/java/com/ceos/spring_vote_21st/member/web/dto/MemberCreateRequestDTO.java
  src/main/java/com/ceos/spring_vote_21st/member/web/dto/MemberResponseDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/domain/Candidate.java
  src/main/java/com/ceos/spring_vote_21st/vote/domain/Election.java
  src/main/java/com/ceos/spring_vote_21st/vote/domain/ElectionStatus.java
  src/main/java/com/ceos/spring_vote_21st/vote/domain/Section.java
  src/main/java/com/ceos/spring_vote_21st/vote/domain/Vote.java
  src/main/java/com/ceos/spring_vote_21st/vote/repository/ElectionRepository.java
  src/main/java/com/ceos/spring_vote_21st/vote/repository/VoteRepository.java
  src/main/java/com/ceos/spring_vote_21st/vote/service/ElectionService.java
  src/main/java/com/ceos/spring_vote_21st/vote/service/VoteService.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/CandidateCreateRequestDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/CandidateModifyRequestDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/CandidateResponseDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/CandidateWithVoteResponseDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/ElectionCreateRequestDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/ElectionResponseDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/VoteCreateRequestDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/VoteResult4CandidateResponseDTO.java
Labels: feature

#13 [PR] master브랜치인 hanihome으로 병합
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/spring-vote-21st.main.iml
  .idea/workspace.xml
  README.md
  build/classes/java/main/com/ceos/spring_vote_21st/CeosBeSpringVote21stApplication.class
  build/classes/java/main/com/ceos/spring_vote_21st/config/SecurityConfig.class
  build/classes/java/main/com/ceos/spring_vote_21st/controller/HealthCheckController.class
  build/classes/java/test/com/ceos/spring_vote_21st/CeosBeSpringVote21stApplicationTests.class
  build/libs/spring-vote-21st-0.0.1-SNAPSHOT-plain.jar
  build/reports/tests/test/classes/com.ceos.spring_vote_21st.CeosBeSpringVote21stApplicationTests.html
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/reports/tests/test/packages/com.ceos.spring_vote_21st.html
  build/resolvedMainClassName
  build/resources/main/application.yaml
  build/test-results/test/TEST-com.ceos.spring_vote_21st.CeosBeSpringVote21stApplicationTests.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/bootJar/MANIFEST.MF
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
  build/tmp/jar/MANIFEST.MF
  src/main/java/com/ceos/spring_vote_21st/auth/config/SecurityConfig.java
  src/main/java/com/ceos/spring_vote_21st/config/SecurityConfig.java
  src/main/java/com/ceos/spring_vote_21st/member/domain/CeosPosition.java
  src/main/java/com/ceos/spring_vote_21st/member/domain/CeosTeam.java
  src/main/java/com/ceos/spring_vote_21st/member/domain/Member.java
  src/main/java/com/ceos/spring_vote_21st/member/repository/MemberRepository.java
  src/main/java/com/ceos/spring_vote_21st/member/service/MemberService.java
  src/main/java/com/ceos/spring_vote_21st/member/web/MemberController.java
  src/main/java/com/ceos/spring_vote_21st/member/web/dto/MemberCreateRequestDTO.java
  src/main/java/com/ceos/spring_vote_21st/member/web/dto/MemberResponseDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/domain/Candidate.java
  src/main/java/com/ceos/spring_vote_21st/vote/domain/Election.java
  src/main/java/com/ceos/spring_vote_21st/vote/domain/ElectionStatus.java
  src/main/java/com/ceos/spring_vote_21st/vote/domain/Section.java
  src/main/java/com/ceos/spring_vote_21st/vote/domain/Vote.java
  src/main/java/com/ceos/spring_vote_21st/vote/repository/ElectionRepository.java
  src/main/java/com/ceos/spring_vote_21st/vote/repository/VoteRepository.java
  src/main/java/com/ceos/spring_vote_21st/vote/service/ElectionService.java
  src/main/java/com/ceos/spring_vote_21st/vote/service/VoteService.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/CandidateCreateRequestDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/CandidateModifyRequestDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/CandidateResponseDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/CandidateWithVoteResponseDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/ElectionCreateRequestDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/ElectionResponseDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/VoteCreateRequestDTO.java
  src/main/java/com/ceos/spring_vote_21st/vote/web/dto/VoteResult4CandidateResponseDTO.java
Labels: documentation, feature

#19 [DOCS] Readme 내용 추가
  .gitignore
  README.md
Labels: documentation

#22 [BUILD] docker-compose에 redis추가
  .dockerignore
  Dockerfile
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/com/ceos/spring_vote_21st/security/auth/application/filter/JwtAuthorizationFilter.java
  src/main/java/com/ceos/spring_vote_21st/security/config/SecurityConfig.java
  src/main/resources/application-docker.yml
Labels: build
